<a href="https://colab.research.google.com/github/MatheusVF1/analise-dados-python/blob/main/An%C3%A1lise_de_dados_Exporta%C3%A7%C3%B5es_fran%C3%A7a.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Link download base de dados: https://drive.google.com/file/d/1ojMHNj6sm1rWZjWdQeDmPCpJMLEnvGHY/view?usp=sharing

### Puxar base de dados

In [53]:
import pandas as pd

tabela = pd.read_csv('exportacoes_franca.csv')

# filtrando as linhas repetidos pegando apenas da Econimic Block da Europa
# tabela = tabela[tabela["Economic Block"] == 'Europe']
tabela = tabela.loc[tabela["Economic Block"] == 'Europe', :]

display(tabela)

,Year,Month,Country,City,SH4 Code,SH4 Description,SH2 Code,SH2 Description,Economic Block,US$ FOB,Net Weight
0,2016,1,France,Águas Mornas - SC,303,"Fish, frozen, excluding fish fillets and other...",3,"Fish and crustaceans, molluscs and other aquat...",Europe,79360,14150
2,2016,1,France,Águas Mornas - SC,304,Fish fillets and other fish meat (whether or n...,3,"Fish and crustaceans, molluscs and other aquat...",Europe,69412,9385
4,2016,1,France,Alfenas - MG,901,"Coffee, whether or not roasted or decaffeinate...",9,"Coffee, tea, maté and spices",Europe,180914,57600
6,2016,1,France,Alta Floresta - MT,4409,Wood (including strips and friezes for parquet...,44,Wood and articles of wood; wood charcoal,Europe,47828,28306
8,2016,1,France,Ananindeua - PA,1211,Plants and parts of plants (including seeds an...,12,"Oil seeds and oleaginous fruits; Grains, Seeds...",Europe,391,22
...,...,...,...,...,...,...,...,...,...,...,...
142350,2020,12,France,Vinhedo - SP,4016,Other articles of vulcanised rubber other than...,40,Rubber and articles thereof,Europe,136,0
142352,2020,12,France,Vinhedo - SP,6806,"Slag wool, rock wool and similar mineral wools...",68,"Articles of stone, plaster, cement, asbestos, ...",Europe,76,50
142354,2020,12,France,Vinhedo - SP,8424,Mechanical appliances (whether or not hand-ope...,84,"Nuclear reactors, boilers, machinery and mecha...",Europe,2316,4
142356,2020,12,France,Vitória de Santo Antão - PE,714,"Manioc, arrowroot, salep, Jerusalem artichokes...",7,Edible vegetables and certain roots and tubers,Europe,27060,26400
142358,2020,12,France,Xapuri - AC,4409,Wood (including strips and friezes for parquet...,44,Wood and articles of wood; wood charcoal,Europe,31111,23045

### Informações Gerais

In [54]:
tabela.info()

# tabela.describe()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 71180 entries, 0 to 142358
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Year             71180 non-null  int64
 1   Month            71180 non-null  int64
 2   Country          71180 non-null  object
 3   City             71180 non-null  object
 4   SH4 Code         71180 non-null  int64
 5   SH4 Description  71180 non-null  object
 6   SH2 Code         71180 non-null  int64
 7   SH2 Description  71180 non-null  object
 8   Economic Block   71180 non-null  object
 9   US$ FOB          71180 non-null  int64
 10  Net Weight       71180 non-null  int64
dtypes: int64(6), object(5)
memory usage: 6.5+ MB

### Como foi a evolução das exportações para a frança (US$) ao longo dos anos?

In [55]:
exportacao_ano = tabela.groupby("Year").sum()
exportacao_ano = exportacao_ano[['US$ FOB']]

# criando função de formatação
def formatar(valor):
    return f"${valor:,.2f}"

# grafico
import plotly.express as px
exportacao_ano = exportacao_ano.reset_index()
grafico = px.line(exportacao_ano, x="Year", y='US$ FOB', title="Exportações para França por Ano")
grafico.update_xaxes(type="category")
grafico.show()


# aplicando a formatação
exportacao_ano["US$ FOB"] = exportacao_ano["US$ FOB"].map(formatar)

display(exportacao_ano)

   Year            US$ FOB
0  2016  $2,307,750,041.00
1  2017  $2,224,352,728.00
2  2018  $2,619,712,208.00
3  2019  $2,609,361,806.00
4  2020  $1,983,797,405.00

### Quais os produtos mais exportados ao longo de todo o período?

In [56]:
# Filtrando o que queremos
exportacao_produto = tabela.groupby("SH4 Description").sum()
exportacao_produto = exportacao_produto[["US$ FOB"]]

# Colocando em Ordem decrescente pelo valor US$
exportacao_produto = exportacao_produto.sort_values("US$ FOB", ascending=False)

# Formatando as moeda
exportacao_produto["US$ FOB"] = exportacao_produto["US$ FOB"].map(formatar) 
display(exportacao_produto)

                                                              US$ FOB
SH4 Description
Soybean oilcake and other solid residue, wh/not...  $2,814,212,320.00
Iron ores and concentrates, including roasted i...  $1,632,140,244.00
Chemical wood pulp, soda or sulphate, other tha...    $922,712,342.00
Coffee, whether or not roasted or decaffeinated...    $536,277,376.00
Other aircraft (for example, helicopters, aerop...    $342,566,535.00
...                                                               ...
Anti-freezing preparations and prepared de-icin...              $5.00
Man-made filament yarn (other than sewing threa...              $5.00
Glass envelopes (including bulbs and tubes), op...              $4.00
Cast glass and rolled glass, in sheets or profi...              $3.00
Drawing or colouring books for children                         $3.00

[935 rows x 1 columns]

### Em 2020 qual cidade mais exportou para a França?

In [57]:
# Filtrando o que queremos
tabela_2020 = tabela.loc[tabela["Year"]==2020, :]

exportacao_cidade_2020 = tabela_2020.groupby("City").sum()
exportacao_cidade_2020 = exportacao_cidade_2020[["US$ FOB"]]

# Colocando em Ordem decrescente pelo valor US$
exportacao_cidade_2020 = exportacao_cidade_2020.sort_values("US$ FOB", ascending=False)

# Formatando as moedas
exportacao_cidade_2020["US$ FOB"] = exportacao_cidade_2020["US$ FOB"].map(formatar) 

display(exportacao_cidade_2020)

                                     US$ FOB
City
Duque de Caxias - RJ         $139,702,798.00
Luís Eduardo Magalhães - BA  $132,664,066.00
Ponta Grossa - PR             $93,888,508.00
São José dos Campos - SP      $86,469,638.00
Rio de Janeiro - RJ           $61,261,107.00
...                                      ...
Não-Me-Toque - RS                     $21.00
Cubatão - SP                          $20.00
Holambra - SP                          $5.00
São Sebastião do Caí - RS              $3.00
Quatro Pontes - PR                     $0.00

[648 rows x 1 columns]

### O que as 2 maiores cidades exportaram tanto?

In [61]:
# Duque de Caxias (filtrando)
tabela_cidade = tabela_2020.loc[tabela_2020["City"]=="Duque de Caxias - RJ", :]
tabela_cidade = tabela_cidade.groupby("SH4 Description").sum()
tabela_cidade = tabela_cidade[["US$ FOB"]]

# Colocando em Ordem decrescente pelos itens mais vendidos
tabela_cidade = tabela_cidade.sort_values("US$ FOB", ascending=False)

# Formatando as moedas
tabela_cidade["US$ FOB"] = tabela_cidade["US$ FOB"].map(formatar)

display(tabela_cidade[:8]) # Pegando apenas os 8 primeiros

                                                           US$ FOB
SH4 Description
Turbo-jets, turbo-propellers and other gas turb...  $82,490,516.00
Crude oil from petroleum and bituminous minerals    $33,610,511.00
Transmission shafts (including cam shafts and c...   $4,897,696.00
Ball or roller bearings                              $4,123,545.00
Screws, bolts, nuts, coach screws, screw hooks,...   $2,109,423.00
Soybean oilcake and other solid residue, wh/not...   $2,007,137.00
Other articles of nickel                             $1,475,623.00
Other articles of iron or steel                      $1,423,564.00